name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti dengan nama branch utama Anda jika berbeda

permissions:
  contents: write  # Menambahkan izin tulis untuk GITHUB_TOKEN

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v3

      # Langkah 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Memperbarui ke Node.js versi 18

      # Langkah 3: Install dependensi frontend
      - name: Install Dependencies
        run: |
          cd magang/frontend
          npm install

      # Langkah 4: Build frontend
      - name: Build Frontend
        run: |
          cd magang/frontend
          npm run build

      # Langkah 5: Menambahkan file .nojekyll
      - name: Create .nojekyll
        run: |
          touch magang/frontend/dist/.nojekyll

      # Langkah 6: Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: magang/frontend/dist
          publish_branch: gh-pages  # Menentukan branch gh-pages sebagai target
